SectionVerb {
	EnableSequence [
		# SPEAKER PLAYBACK
		cset "name='ASI1 Sel' LeftRightDiv2"
		# Enable Tertiary MI2S mixer on MultiMedia1
		cset "name='TERT_MI2S_RX Audio Mixer MultiMedia1' 1"
	]

	DisableSequence [
		# Disable Tertiary MI2S mixer on MultiMedia1
		cset "name='TERT_MI2S_RX Audio Mixer MultiMedia1' 0"
	]

	# Set initial volumes
	BootSequence [
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker playback"

	Value {
		PlaybackPriority 150
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels 1
	}
}
